# docker-compose.yml (in project root)
version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: store-layout-db
    restart: always
    environment:
      POSTGRES_USER: store_admin
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: store_layout_designer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Optional: Database admin interface
  pgadmin:
    image: dpage/pgadmin4
    container_name: store-layout-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@store.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
